# render.yaml — Infraestructura como código para Render
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: wizzlife-taskmanager
    runtime: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --worker-class gthread --timeout 60"
    healthCheckPath: /api/schema/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "wizzlife-technicaltest.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: wizzlife-db
          property: connectionString
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://wizzlife-technicaltest.onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: ACCESS_TOKEN_LIFETIME_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_LIFETIME_DAYS
        value: "7"
      - key: PYTHON_VERSION
        value: "3.12.0"

databases:
  - name: wizzlife-db
    databaseName: wizzlife_db
    user: wizzlife
    region: oregon
    plan: free
